# Data Transformation

###Data Exploration and pre-processing

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/adult_with_headers (1).csv')

In [ ]:
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,0.0,40.0,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,0.0,40.0,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,0.0,40.0,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17918,48,Federal-gov,247043,HS-grad,9,Divorced,Adm-clerical,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
17919,40,Private,187702,Bachelors,13,Never-married,Tech-support,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
17920,62,Private,41718,10th,6,Married-civ-spouse,Sales,Husband,White,Male,0.0,0.0,35.0,United-States,<=50K
17921,37,Private,151835,Prof-school,15,Married-civ-spouse,Sales,Husband,White,Male,0.0,0.0,45.0,United-States,>50K
17922,18,Private,118938,11th,7,Never-married,Sales,Own-child,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17923 entries, 0 to 17922
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             17923 non-null  int64
 1   workclass       17923 non-null  object
 2   fnlwgt          17923 non-null  int64
 3   education       17923 non-null  object
 4   education_num   17923 non-null  int64
 5   marital_status  17923 non-null  object
 6   occupation      17923 non-null  object
 7   relationship    17923 non-null  object
 8   race            17922 non-null  object
 9   sex             17922 non-null  object
 10  capital_gain    17922 non-null  float64
 11  capital_loss    17922 non-null  float64
 12  hours_per_week  17922 non-null  float64
 13  native_country  17922 non-null  object
 14  income          17922 non-null  object
dtypes: float64(3), int64(3), object(9)
memory usage: 2.1+ MB

In [ ]:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,17923.000000,1.792300e+04,17923.000000,17922.000000,17922.000000,17922.000000
mean,38.550243,1.901854e+05,10.090219,1050.742272,87.770282,40.414407
std,13.623031,1.054434e+05,2.559689,7281.141976,402.532485,12.274417
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.186945e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.789150e+05,10.000000,0.000000,0.000000,40.000000
75%,47.500000,2.378490e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

# Basic Statistics Interpretation

- Mean: Represents the average value of each numerical feature.
- Standard Deviation: Shows how much the data varies from the mean.
- Minimum and Maximum: Indicate the range of values.
- Quartiles (25%, 50%, 75%): Help understand data distribution.

Observations:
- Some features have large differences between min and max, indicating high variability.
- Presence of skewness is observed in features like 'capital_gain'.
- Median (50%) helps identify central tendency and detect skewness.

Overall, statistical summary helps in understanding the distribution and spread of data before transformation.

In [ ]:
df.describe(include='object')

,workclass,education,marital_status,occupation,relationship,race,sex,native_country,income
count,17923,17923,17923,17923,17923,17922,17922,17922,17922
unique,9,16,7,15,6,5,2,41,2
top,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,<=50K
freq,12507,5856,8229,2278,7226,15355,12000,16033,13637

In [ ]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              1
sex               1
capital_gain      1
capital_loss      1
hours_per_week    1
native_country    1
income            1
dtype: int64

In [ ]:
df.replace(" ?", np.nan, inplace=True)
print(df.isnull().sum())

age                  0
workclass         1005
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1008
relationship         0
race                 1
sex                  1
capital_gain         1
capital_loss         1
hours_per_week       1
native_country     323
income               1
dtype: int64

###Handling the missing values

In [ ]:
df.dropna(inplace=True)

In [ ]:
# Numerical features → Median
num_cols = df.select_dtypes(include=['int64','float64']).columns
for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

# Categorical features → Mode
cat_cols = df.select_dtypes(include=['object']).columns
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipykernel_4388/813503494.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/tmp/ipykernel_4388/813503494.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

###Scaling Techniques

####A)Standard Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_standard = df.copy()
df_standard[num_cols] = scaler.fit_transform(df[num_cols])

####B)Min-Max Scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
df_minmax = df.copy()
df_minmax[num_cols] = minmax.fit_transform(df[num_cols])

###Encoding Techniques

####Separate Categorical columns

In [ ]:
cat_cols = df.select_dtypes(include='object').columns

####A)One-Hot Encoding (<5 categories)

In [ ]:
small_cat = [col for col in cat_cols if df[col].nunique() < 5]

df = pd.get_dummies(df, columns=small_cat, drop_first=True)

###B)Label Encoding(>5 categories)

In [ ]:
from sklearn.preprocessing import LabelEncoder
cat_cols = df.select_dtypes(include='object').columns

large_cat = [col for col in cat_cols if df[col].nunique() >= 5]

le = LabelEncoder()

for col in large_cat:
    df[col] = le.fit_transform(df[col])

## Feature Engineering
### Create 2 New Features
####Capital Total Feature

In [ ]:
df['total_capital'] = df['capital_gain'] + df['capital_loss']

####Education Level Feature

In [ ]:
education_order = {
    'Preschool':1, '1st-4th':2, '5th-6th':3, '7th-8th':4,
    '9th':5, '10th':6, '11th':7, '12th':8,
    'HS-grad':9, 'Some-college':10,
    'Assoc-voc':11, 'Assoc-acdm':12,
    'Bachelors':13, 'Masters':14,
    'Prof-school':15, 'Doctorate':16
}

df['education_level'] = df['education'].map(education_order)

####Skewed Feature Transformation

In [ ]:
print(df[num_cols].skew())

age                0.543965
fnlwgt             1.483183
education_num     -0.289495
capital_gain      12.103122
capital_loss       4.491698
hours_per_week     0.311570
dtype: float64

In [ ]:
#By applying Log Transformation
df['capital_gain_log'] = np.log1p(df['capital_gain'])

# Feature Engineering Explanation

1. Total Capital Feature:
The new feature 'total_capital' is created by combining 'capital_gain' and 'capital_loss'.

Rationale:
- Instead of analyzing gain and loss separately, combining them provides a better representation of overall financial status.
- This helps the model understand the net financial impact more effectively.

2. Education Level Feature:
The 'education_level' feature converts categorical education values into ordered numerical values.

Rationale:
- Education has a natural order (e.g., Preschool < Bachelors < Doctorate).
- Converting it into numerical form helps the model capture this hierarchy.
- It improves model performance compared to treating it as simple categories.

##Iosation Forest (OutlierDetection)

In [ ]:
from sklearn.ensemble import IsolationForest

iso = IsolationForest(contamination=0.05)
outliers = iso.fit_predict(df[num_cols])

df['outlier'] = outliers
df = df[df['outlier'] == 1]  # Keep non-outliers

##PPS Score(Predictive Power Score)

In [ ]:
#By Installing the ppscore
!pip install ppscore --no-deps

Collecting ppscore
  Downloading ppscore-1.3.1.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: ppscore
  Building wheel for ppscore (setup.py) ... done
  Created wheel for ppscore: filename=ppscore-1.3.1-py2.py3-none-any.whl size=13180 sha256=23a2cf8a362ceec4173c95c933703f35bb44d9bc33bbe3e5b79d78fbf227f179
  Stored in directory: /root/.cache/pip/wheels/84/0d/d6/ec295c574356939e9877f87c4eb195ba97440b0cd97cadf32a
Successfully built ppscore
Installing collected packages: ppscore
Successfully installed ppscore-1.3.1

In [ ]:
import ppscore as pps

In [ ]:
pps_matrix = pps.matrix(df)
print(pps_matrix)

           x                 y       ppscore  \
0        age               age  1.000000e+00
1        age         workclass  0.000000e+00
2        age            fnlwgt  0.000000e+00
3        age         education  0.000000e+00
4        age     education_num  0.000000e+00
..       ...               ...           ...
356  outlier      income_ >50K  1.327974e-07
357  outlier     total_capital  0.000000e+00
358  outlier   education_level  0.000000e+00
359  outlier  capital_gain_log  0.000000e+00
360  outlier           outlier  1.000000e+00

                                  case  is_valid_score               metric  \
0                       predict_itself            True                 None
1                           regression            True  mean absolute error
2                           regression            True  mean absolute error
3                           regression            True  mean absolute error
4                           regression            True  mean absolute error
..                                 ...             ...                  ...
356                     classification            True          weighted F1
357                         regression            True  mean absolute error
358  empty_dataframe_after_dropping_na           False                 None
359                         regression            True  mean absolute error
360                     predict_itself            True                 None

     baseline_score   model_score                     model
0          0.000000      1.000000                      None
1          0.440000      0.571173   DecisionTreeRegressor()
2      75671.873800  76598.703994   DecisionTreeRegressor()
3          2.658400      2.741214   DecisionTreeRegressor()
4          1.794400      1.836467   DecisionTreeRegressor()
..              ...           ...                       ...
356        0.676761      0.676761  DecisionTreeClassifier()
357      462.728400    844.032566   DecisionTreeRegressor()
358        0.000000      0.000000                      None
359        0.581916      1.084519   DecisionTreeRegressor()
360        0.000000      1.000000                      None

[361 rows x 9 columns]

#Final outcome:
####1. Missing values handled
####2. Data scaled
####3. Encoding applied
####4. New features created
####5. Skewness handled
####6. Outliers removed
####7. Feature relationships analyzed

# Skewness Interpretation

- Positive skewness indicates long tail on the right side.
- Log transformation was applied to reduce skewness.
- This helps improve model performance and normalization.

# Conclusion

- Missing values were successfully handled using appropriate techniques such as median for numerical features and mode for categorical features.
- Feature scaling techniques like Standardization and Min-Max Scaling were applied to normalize the data and ensure all features are on a similar scale.
- Categorical variables were encoded using One-Hot Encoding and Label Encoding based on the number of categories.
- New features such as 'total_capital' and 'education_level' were created to improve the representation of the data and enhance model understanding.
- Log transformation was applied to reduce skewness in highly skewed features like 'capital_gain'.
- Outliers were detected and removed using Isolation Forest to improve data quality.
- Predictive Power Score (PPS) was used to analyze relationships between features.

Overall, data transformation techniques improved the quality, consistency, and usability of the dataset, making it suitable for building accurate and efficient machine learning models.